name: ringo_media_test
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  go_router: ^14.2.1
  google_fonts: ^6.2.1
  flutter_feather_icons: ^2.0.0+1
  flutter_svg: ^2.0.10+1
  flutter_riverpod: ^2.5.1
  el_tooltip: ^2.0.0
  iconly: ^1.0.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  easy_date_timeline: ^1.1.3
  calendar_view: ^1.2.0
  intl: ^0.19.0
  collection: ^1.18.0
  table_calendar: ^3.1.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1

flutter:

  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - google_fonts/
